-- 사용자별 기본 설정 테이블
CREATE TABLE `user_custom_setting` (
    `setting_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `company_id` INT(11) NOT NULL DEFAULT 1 COMMENT '회사 ID (외래키)',
    `user_id` INT(11) NOT NULL COMMENT '사용자 ID (외래키)',
    
    -- 초기 화면 설정
    `default_menu_code` VARCHAR(50) DEFAULT NULL COMMENT '로그인 후 초기 진입 메뉴 코드 (menu 테이블 code 참조)',
    `default_page_path` VARCHAR(300) DEFAULT NULL COMMENT '로그인 후 초기 진입 페이지 경로',
    
    -- 모듈별 초기 화면 설정 (JSON 형태로 저장)
    `module_default_settings` JSON DEFAULT NULL COMMENT '모듈별 초기 화면 설정 ({"ct": {"action": "read", "tab": "request"}})',
    
    -- UI 설정
    `theme_mode` VARCHAR(20) DEFAULT 'light' COMMENT '테마 모드 (light: 라이트 모드, dark: 다크 모드)',
    `sidebar_collapsed` TINYINT(1) DEFAULT 0 COMMENT '사이드바 접힘 상태 (1: 접힘, 0: 펼침)',
    `items_per_page` INT(11) DEFAULT 15 COMMENT '페이지당 표시 항목 수',
    
    -- 데이터 표시 설정
    `date_format` VARCHAR(20) DEFAULT 'YYYY-MM-DD' COMMENT '날짜 형식',
    `time_format` VARCHAR(20) DEFAULT 'HH:mm:ss' COMMENT '시간 형식',
    `language` VARCHAR(10) DEFAULT 'ko' COMMENT '언어 설정 (ko: 한국어, en: 영어)',
    
    -- 알림 설정
    `notification_enabled` TINYINT(1) DEFAULT 1 COMMENT '알림 활성화 여부 (1: 활성, 0: 비활성)',
    `notification_email` TINYINT(1) DEFAULT 1 COMMENT '이메일 알림 수신 여부 (1: 활성, 0: 비활성)',
    `notification_sms` TINYINT(1) DEFAULT 0 COMMENT 'SMS 알림 수신 여부 (1: 활성, 0: 비활성)',
    
    -- 기타 설정
    `custom_settings` JSON DEFAULT NULL COMMENT '기타 커스텀 설정 (확장 가능한 JSON 필드)',
    
    `is_active` TINYINT(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
    `sort_order` INT(11) DEFAULT 1 COMMENT '정렬 순서',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '생성일시',
    `created_by` INT(11) DEFAULT NULL COMMENT '생성자 ID (외래키)',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '수정일시',
    `updated_by` INT(11) DEFAULT NULL COMMENT '수정자 ID (외래키)',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '삭제일시 (Soft Delete)',
    `deleted_by` INT(11) DEFAULT NULL COMMENT '삭제자 ID (외래키)',
    
    PRIMARY KEY (`setting_id`),
    UNIQUE KEY `uk_user_id` (`user_id`) COMMENT '사용자별 설정 중복 방지 (1인 1설정)',
    KEY `idx_active` (`is_active`, `user_id`) COMMENT '활성 설정 조회',
    KEY `idx_company_active_sort` (`company_id`, `is_active`, `sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자별 기본 설정 테이블';

-- 사용자 커스텀 설정 초기 데이터 삽입
INSERT INTO `user_custom_setting` (
  `company_id`, `user_id`, `default_menu_code`, `default_page_path`, 
  `module_default_settings`, `theme_mode`, `sidebar_collapsed`, `items_per_page`, 
  `date_format`, `time_format`, `language`, 
  `notification_enabled`, `notification_email`, `notification_sms`, `is_active`
) VALUES
(1, 1, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 2, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 3, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 4, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 5, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 6, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 7, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 8, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 9, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 10, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 11, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 12, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 13, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 14, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 15, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 16, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 17, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 18, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 19, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 20, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 21, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1),
(1, 22, 'ct_request', '/ct/request/read', '{"ct": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "ct"}}, "internal": {"request": {"action": "create"}, "testReport": {"action": "read"}, "schedule": {"action": "internal"}}, "external": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "external"}}, "preservative": {"request": {"action": "read"}, "testReport": {"action": "read"}, "schedule": {"action": "preservative"}}}', 'light', 0, 15, 'YYYY-MM-DD', 'HH:mm:ss', 'ko', 1, 1, 0, 1);