-- 결재 문서 테이블
CREATE TABLE `approval_document` (
  `approval_document_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `approval_template_id` int(11) DEFAULT NULL COMMENT '결재 양식 pk(외래키) - 사용한 템플릿 추적용',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `document_type` varchar(20) DEFAULT NULL COMMENT '문서 유형 (Ex. CT_REQ: CT의뢰, CT_TEST: 시험성적서)',
  `document_id` int(11) DEFAULT NULL COMMENT '문서 ID (ct_request_id 또는 ct_test_report_id)',
  `document_title` varchar(200) DEFAULT NULL COMMENT '문서 제목 (CT 번호 등)',
  `requester_id` int(11) DEFAULT NULL COMMENT '결재 요청자 pk',
  `request_date` datetime DEFAULT NULL COMMENT '결재 요청일시',
  `complete_date` datetime DEFAULT NULL COMMENT '결재 완료일시',
  `current_step` int(11) DEFAULT 1 COMMENT '현재 결재 단계',
  `approval_status` varchar(20) DEFAULT 'PENDING' COMMENT '결재 상태 (PENDING: 대기, APPROVED: 승인완료, REJECTED: 반려, CANCELED: 취소)',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`approval_document_id`),
  KEY `idx_approval_template_id` (`approval_template_id`) COMMENT '템플릿별 조회',
  KEY `idx_company_active_sort` (`company_id`,`is_active`,`sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스',
  KEY `idx_document_type` (`document_type`) COMMENT '문서 유형별 조회',
  KEY `idx_document_id` (`document_id`) COMMENT '문서 ID별 조회',
  KEY `idx_requester_id` (`requester_id`) COMMENT '요청자별 조회',
  KEY `idx_approval_status` (`approval_status`) COMMENT '결재 상태별 조회',
  KEY `idx_request_date` (`request_date`) COMMENT '요청일자별 조회'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='결재 문서 테이블';