-- 결재 이력 테이블
CREATE TABLE `approval_history` (
  `approval_history_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `approval_document_id` int(11) NULL COMMENT '결재 문서 pk(외래키)',
  `approval_line_id` int(11) NULL COMMENT '결재선 pk(외래키) - 어느 결재선에서의 처분인지 추적',
  `step` int(11) DEFAULT NULL COMMENT '결재 단계 (1, 2, 3...) - 이력 발생 시점의 단계',
  `action_type` varchar(20) NOT NULL COMMENT '행동 유형 (Ex. REQUEST: 요청, APPROVE_REQUEST: 승인처리, REJECT_REQUEST: 반려처리, CANCEL_REQUEST: 취소, REASSIGN: 재배정, DELEGATE: 위임)',
  `previous_status` varchar(20) NOT NULL DEFAULT 'NONE' COMMENT '이전 상태 (NONE: 초기, PENDING, APPROVED, REJECTED, SKIPPED, CANCELED 등)',
  `new_status` varchar(20) NOT NULL COMMENT '변경된 상태 (PENDING, APPROVED, REJECTED 등)',
  `actor_id` int(11) NULL COMMENT '행동 수행자 pk (결재자, 요청자 등) (외래키)',
  `actor_name` varchar(100) DEFAULT NULL COMMENT '행동 수행자명 (스냅샷)',
  `actor_user_grade_id` int(11) DEFAULT NULL COMMENT '행동 수행 시점의 직급 pk',
  `actor_user_grade_name` varchar(50) DEFAULT NULL COMMENT '행동 수행 시점의 직급명 (스냅샷)',
  `actor_department_id` int(11) DEFAULT NULL COMMENT '행동 수행 시점의 부서 pk',
  `actor_department_name` varchar(100) DEFAULT NULL COMMENT '행동 수행 시점의 부서명 (스냅샷)',
  `delegated_from_user_id` int(11) DEFAULT NULL COMMENT '위임자 pk (대리 결재인 경우)',
  `delegated_from_user_name` varchar(100) DEFAULT NULL COMMENT '위임자명 (스냅샷)',
  `action_date` datetime NOT NULL DEFAULT current_timestamp() COMMENT '행동 수행 일시',
  `comment` text DEFAULT NULL COMMENT '의견/사유',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP 주소 (보안 추적용)',
  `user_agent` varchar(255) DEFAULT NULL COMMENT 'User Agent (접속 환경)',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`approval_history_id`),
  KEY `idx_company_active_sort` (`company_id`,`is_active`,`sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스',
  KEY `idx_approval_document_id` (`approval_document_id`) COMMENT '결재 문서별 이력 조회',
  KEY `idx_approval_line_id` (`approval_line_id`) COMMENT '결재선별 이력 조회',
  KEY `idx_actor_id` (`actor_id`) COMMENT '행동 수행자별 조회',
  KEY `idx_action_type` (`action_type`) COMMENT '행동 유형별 조회',
  KEY `idx_action_date` (`action_date`) COMMENT '일시별 조회'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='결재 이력 테이블 - 모든 결재 행동과 상태 변경을 추적';