-- 고급 결재 기능이 추가된 결재선 테이블
CREATE TABLE `approval_line` (
  `approval_line_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `approval_document_id` int(11) DEFAULT NULL COMMENT '결재 문서 pk (외래키)',
  `document_type` varchar(20) DEFAULT NULL COMMENT '문서 유형 (CT_REQ, CT_TEST 등)',
  `step` int(11) NOT NULL COMMENT '결재 단계 (1, 2, 3...)',
  `user_grade_id` int(11) DEFAULT NULL COMMENT '필요 직급 pk (수석, 이사 등) (외래키)',
  `approver_id` int(11) DEFAULT NULL COMMENT '결재자 pk (외래키)',
  `department_id` int(11) DEFAULT NULL COMMENT '부서 ID (외래키)',
  `team_code` varchar(20) DEFAULT NULL COMMENT '팀 코드(결재 부서)',
  `approval_type` varchar(20) DEFAULT 'APPROVE' COMMENT '결재 유형 (APPROVE: 결재, AGREE: 합의, REFERENCE: 참조)',
  `is_parallel` tinyint(1) DEFAULT 0 COMMENT '병렬 결재 여부 (1: 병렬, 0: 순차) - 같은 step의 여러 결재자가 동시에 결재',
  `parallel_group_id` varchar(50) DEFAULT NULL COMMENT '병렬 그룹 ID (같은 step 내에서 병렬 처리할 그룹)',
  `parallel_approval_rule` varchar(20) DEFAULT 'ALL' COMMENT '병렬 결재 규칙 (ALL: 전원 승인, ANY: 1명 승인, MAJORITY: 과반수)',
  `delegated_from_user_id` int(11) DEFAULT NULL COMMENT '위임자 pk (외래키) - 원래 결재자',
  `delegation_start_date` datetime DEFAULT NULL COMMENT '위임 시작일',
  `delegation_end_date` datetime DEFAULT NULL COMMENT '위임 종료일',
  `delegation_reason` text DEFAULT NULL COMMENT '위임 사유',
  `condition_type` varchar(20) DEFAULT NULL COMMENT '조건 유형 (AMOUNT: 금액, PRIORITY: 우선순위, CUSTOM: 커스텀)',
  `condition_value` varchar(100) DEFAULT NULL COMMENT '조건 값 (JSON 또는 단순 값)',
  `approval_status` varchar(20) DEFAULT 'PENDING' COMMENT '결재 상태 (PENDING: 대기, APPROVED: 승인, REJECTED: 반려, SKIPPED: 건너뜀, CANCELED: 취소, DELEGATED: 위임됨)',
  `approval_date` datetime DEFAULT NULL COMMENT '결재일시',
  `approval_comment` text DEFAULT NULL COMMENT '결재 의견',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번 (같은 step 내 정렬)',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`approval_line_id`),
  KEY `idx_company_active_sort` (`company_id`,`is_active`,`sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스',
  KEY `idx_approval_document_id` (`approval_document_id`) COMMENT '결재 문서별 조회',
  KEY `idx_approver_id` (`approver_id`) COMMENT '결재자별 조회',
  KEY `idx_approval_status` (`approval_status`) COMMENT '결재 상태별 조회',
  KEY `idx_step` (`step`) COMMENT '단계별 조회',
  KEY `idx_document_step` (`approval_document_id`,`step`) COMMENT '문서-단계 복합 조회',
  KEY `idx_approver_status` (`approver_id`,`approval_status`) COMMENT '결재자-상태 복합 조회',
  KEY `idx_parallel_group` (`parallel_group_id`) COMMENT '병렬 그룹 조회',
  KEY `idx_delegated_from` (`delegated_from_user_id`) COMMENT '위임자 조회',
  KEY `idx_approval_type` (`approval_type`) COMMENT '결재 유형별 조회',
  KEY `idx_document_type` (`document_type`) COMMENT '문서 유형별 조회',
  KEY `idx_document_type_status` (`document_type`,`approval_status`) COMMENT '문서 유형-상태 복합 조회'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='결재선 테이블 - 고급 기능 포함';