-- CT 의뢰 테이블
CREATE TABLE `ct_request` (
  `ct_request_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `ct_request_date` datetime DEFAULT NULL COMMENT 'CT 의뢰일자',
  `ct_no` varchar(20) NOT NULL COMMENT 'CT 번호',
  `ct_test_seq` smallint(6) DEFAULT NULL COMMENT '차수',
  `ct_status` varchar(20) DEFAULT 'REQUESTED' COMMENT 'CT 상태 (REQUESTED, IN_PROGRESS, COMPLETED, SUSPENDED, CANCELLED)',
  `client_id` int(11) DEFAULT NULL COMMENT '고객사 pk(외래키)',
  `sample_id` int(11) DEFAULT NULL COMMENT '샘플 pk(외래키)',
  `ct_lab_no` varchar(30) DEFAULT NULL COMMENT '랩넘버',
  `sales_manager_id` int(11) DEFAULT NULL COMMENT '영업담당자 pk(외래키)',
  `labs_manager_id` int(11) DEFAULT NULL COMMENT '제형담당자 pk(외래키)',
  `labs_manage_department_id` int(11) DEFAULT NULL COMMENT '제형담당부서 pk(외래키)',
  `ct_type` varchar(10) DEFAULT NULL COMMENT 'CT 유형',
  `material_supplier_id` int(11) DEFAULT NULL COMMENT '자재 업체 pk(외래키)',
  `material_large_category_id` int(11) DEFAULT NULL COMMENT '자재 유형 대분류 pk(외래키)',
  `material_sub_category` varchar(200) DEFAULT NULL COMMENT '자재 유형 중분류',
  `material_description` varchar(500) DEFAULT NULL COMMENT '자재 정보',
  `material_quality` varchar(500) DEFAULT NULL COMMENT '자재 품질',
  `material_quantity` int(11) DEFAULT NULL COMMENT '자재수량',
  `sample_quantity` int(11) DEFAULT NULL COMMENT '샘플수량',
  `desired_volume` decimal(19,5) DEFAULT NULL COMMENT '희망 용량',
  `desired_volume_unit_id` int(11) DEFAULT NULL COMMENT '희망 용량 단위',
  `sleeve_length` decimal(19,5) DEFAULT NULL COMMENT '슬리브 요청 길이',
  `is_emergency` tinyint(1) NOT NULL DEFAULT 0 COMMENT '긴급 여부 (1: 활성, 0: 비활성)',
  `is_cpnp` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'CPNP 여부 (1: 활성, 0: 비활성)',
  `is_eng` tinyint(1) NOT NULL DEFAULT 0 COMMENT '영문 여부 (1: 활성, 0: 비활성)',
  `request_content` text DEFAULT NULL COMMENT '의뢰 내용',
  `request_remark` text DEFAULT NULL COMMENT '의뢰 비고',
  `material_request_date` datetime DEFAULT NULL COMMENT '자재 의뢰일자',
  `sample_type_id` int(11) DEFAULT NULL COMMENT '제형 유형 pk(외래키)',
  `required_bulk_volume` decimal(19,5) DEFAULT NULL COMMENT '필요 벌크량',
  `required_bulk_volume_unit_id` int(11) DEFAULT NULL COMMENT '필요 벌크량 용량 단위 pk(외래키)',
  `request_bulk_volume` decimal(19,5) DEFAULT NULL COMMENT '의뢰 벌크량',
  `request_bulk_volume_unit_id` int(11) DEFAULT NULL COMMENT '의뢰 벌크량 용량 단위 pk(외래키)',
  `net_capacity` decimal(19,5) DEFAULT NULL COMMENT '적정표시용량(순용량)',
  `net_capacity_unit_id` int(11) DEFAULT NULL COMMENT '적정표시용량(순용량) 단위 pk(외래키)',
  `sample_etc` text DEFAULT NULL COMMENT '기타 특이사항',
  `sample_remark` text DEFAULT NULL COMMENT '제형 비고',
  `ct_receipt_date` datetime DEFAULT NULL COMMENT 'CT 접수일자',
  `ct_due_date` datetime DEFAULT NULL COMMENT 'CT 완료일자',
  `ct_manager_id` int(11) DEFAULT NULL COMMENT 'CT 담당자 pk(외래키)',
  `is_ct_suspend` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'CT 보류',
  `ct_suspend_reason` text DEFAULT NULL COMMENT 'CT 보류 사유',
  `ct_manage_summary` text DEFAULT NULL COMMENT 'CT 관리사항 기타 특이사항',
  `ct_manage_remark` text DEFAULT NULL COMMENT 'CT 관리사항 비고',
  `approve_id` int(11) DEFAULT NULL COMMENT '결재 문서 pk(외래키)',
  `judgment_id` int(11) DEFAULT NULL COMMENT '판정 pk(외래키)',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`ct_request_id`),
  KEY `idx_ct_request_date` (`ct_request_date`) COMMENT '기간별 조회',
  KEY `idx_client_id` (`client_id`) COMMENT '고객사별 조회',
  KEY `idx_sales_manager_id` (`sales_manager_id`) COMMENT '영업담당자별 CT 목록',
  KEY `idx_labs_manager` (`labs_manager_id`) COMMENT '제형담당자별 CT 목록',
  KEY `idx_ct_manager` (`ct_manager_id`) COMMENT 'CT담당자별 업무 목록',
  KEY `idx_labs_manage_department_id` (`labs_manage_department_id`) COMMENT '제형담당부서 목록',
  KEY `idx_is_emergency` (`is_emergency`) COMMENT '긴급 건 우선 처리',
  KEY `idx_is_cpnp` (`is_cpnp`) COMMENT 'CPNP 시험 필터링',
  KEY `idx_is_eng` (`is_eng`) COMMENT '영문 작업 필터링',
  KEY `idx_material_supplier` (`material_supplier_id`) COMMENT '자재업체별 조회',
  KEY `idx_material_large_category_id` (`material_large_category_id`) COMMENT '자재 대분류별 통계',
  KEY `idx_client_active` (`client_id`,`is_active`,`ct_request_date`) COMMENT '고객사별 활성 CT 조회',
  KEY `idx_manager_status` (`ct_manager_id`,`is_ct_suspend`,`is_active`) COMMENT '담당자별 미완료 업무 조회',
  KEY `idx_company_active_sort` (`company_id`, `is_active`, `sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스',
  KEY `idx_created_at` (`created_at`) COMMENT '최신순 정렬'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CT 의뢰 테이블';