-- CT 시험 성적서 테이블
CREATE TABLE `ct_test_report` (
  `ct_test_report_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `ct_request_id` int(11) NULL COMMENT 'CT 의뢰 pk(외래키)',
  `ct_no` varchar(50) NOT NULL COMMENT 'CT 번호',
  `requester_id` int(11) DEFAULT NULL COMMENT '시험의뢰자 pk(외래키)',
  `specific` double DEFAULT NULL COMMENT '비중',
  `sample_id` int(11) DEFAULT NULL COMMENT '샘플 pk(외래키)',
  `formulation_manager_id` int(11) DEFAULT NULL COMMENT '제형담당자 pk(외래키)',
  `viscosity_hardness` varchar(100) DEFAULT NULL COMMENT '점도/경도',
  `desired_volume` varchar(200) DEFAULT NULL COMMENT '희망 용량',
  `lab_no` varchar(100) DEFAULT NULL COMMENT '랩넘버',
  `test_start_date` datetime DEFAULT NULL COMMENT '시험 시작일',
  `test_end_date` datetime DEFAULT NULL COMMENT '시험 종료일',
  `request_order` varchar(100) DEFAULT NULL COMMENT '의뢰차수',
  `request_quantity` int(11) DEFAULT NULL COMMENT '의뢰수량',
  `formulation_notes` text DEFAULT NULL COMMENT '제형 특이사항',
  `material_supplier_id` int(11) DEFAULT NULL COMMENT '자재 업체 pk(외래키)',
  `material_info` text DEFAULT NULL COMMENT '자재 정보',
  `material_image` text DEFAULT NULL COMMENT '자재 이미지',
  `judgment_date` datetime DEFAULT NULL COMMENT '판정일',
  `daily_judgment_id` int(11) DEFAULT NULL COMMENT '일일 판정 pk(외래키)',
  `final_judgment_id` int(11) DEFAULT NULL COMMENT '최종 판정 pk(외래키)',
  `tester_id` int(11) DEFAULT NULL COMMENT '시험자 pk(외래키)',
  `approver_id` int(11) DEFAULT NULL COMMENT '승인자 pk(외래키)',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`ct_test_report_id`),   
  KEY `idx_requester_id` (`requester_id`) COMMENT '의뢰자별 조회',
  KEY `idx_sample_id` (`sample_id`) COMMENT '샘플별 조회',
  KEY `idx_formulation_manager_id` (`formulation_manager_id`) COMMENT '제형담당자별 조회',
  KEY `idx_material_supplier_id` (`material_supplier_id`) COMMENT '자재업체별 조회',
  KEY `idx_tester_id` (`tester_id`) COMMENT '시험자별 조회',
  KEY `idx_approver_id` (`approver_id`) COMMENT '승인자별 조회',
  KEY `idx_test_start_date` (`test_start_date`) COMMENT '시험 시작일별 조회',
  KEY `idx_test_end_date` (`test_end_date`) COMMENT '시험 종료일별 조회',
  KEY `idx_judgment_date` (`judgment_date`) COMMENT '판정일별 조회',
  KEY `idx_active_created` (`is_active`,`created_at`) COMMENT '활성 성적서 최신순',
  KEY `idx_requester_active` (`requester_id`,`is_active`,`test_start_date`) COMMENT '의뢰자별 활성 성적서',
  KEY `idx_tester_active` (`tester_id`,`is_active`) COMMENT '시험자별 미완료 작업',
  KEY `idx_created_at` (`created_at`) COMMENT '최신순 정렬',
  KEY `idx_company_active_sort` (`company_id`, `is_active`, `sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CT 시험 성적서 테이블';