-- 부서 관리 테이블
CREATE TABLE `department` (
  `department_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `company_id` int(11) NOT NULL DEFAULT 1 COMMENT '회사 pk(외래키)',
  `company_code` varchar(30) DEFAULT NULL COMMENT '회사코드',
  `company_name` varchar(30) DEFAULT NULL COMMENT '회사명',
  `division_code` varchar(30) DEFAULT NULL COMMENT '사업부코드',
  `division_name` varchar(30) DEFAULT NULL COMMENT '사업부명',
  `department_code` varchar(30) DEFAULT NULL COMMENT '본부코드',
  `department_name` varchar(30) DEFAULT NULL COMMENT '본부명',
  `team_code` varchar(30) DEFAULT NULL COMMENT '팀코드',
  `team_name` varchar(30) DEFAULT NULL COMMENT '팀명',
  `part_code` varchar(30) DEFAULT NULL COMMENT '파트코드',
  `part_name` varchar(30) DEFAULT NULL COMMENT '파트명',
  `temp_company_seq` varchar(50) DEFAULT NULL COMMENT '마이그레이션 시 원본 테이블 CompanySeq',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 여부 (1: 활성, 0: 비활성)',
  `sort_order` int(11) DEFAULT 1 COMMENT '정렬 순번',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일',
  `created_by` int(11) DEFAULT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일',
  `updated_by` int(11) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일',
  `deleted_by` int(11) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`department_id`),
  KEY `idx_company_active_sort` (`company_id`,`is_active`,`sort_order`) COMMENT '회사, 활성 여부 및 정렬 순번 인덱스'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부서 관리 테이블';